# Generated by Django 3.2.9 on 2024-02-19 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptionpackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('package_name', models.CharField(max_length=80, null=True)),
                ('no_free_months', models.IntegerField(default=0)),
                ('no_discounted_months', models.IntegerField(default=0)),
                ('discounted_price', models.IntegerField(default=0)),
                ('base_price', models.IntegerField(default=0)),
                ('package_detail', models.CharField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'subscription_package',
            },
        ),
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripeCustomerId', models.CharField(max_length=255)),
                ('stripeSubscriptionId', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stripe_customer',
            },
        ),
    ]
