# Generated by Django 3.2.9 on 2024-02-19 16:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Logfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=5)),
                ('entry_date', models.DateField(default=datetime.date.today)),
                ('sleep_diary_date', models.DateField()),
                ('patient_id', models.CharField(max_length=5)),
                ('user_type', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'log_detail',
            },
        ),
        migrations.CreateModel(
            name='PatientEfficiency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=5)),
                ('week_no', models.CharField(max_length=2)),
                ('sleep_efficiency', models.CharField(max_length=10, null=True)),
                ('bed_time', models.CharField(max_length=10, null=True)),
                ('sugg_wake_up', models.CharField(max_length=10, null=True)),
                ('base_time', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'patient_efficieny',
            },
        ),
        migrations.CreateModel(
            name='ProviderCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.CharField(max_length=5)),
                ('subscription_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('name_on_card', models.CharField(max_length=40)),
                ('exp_date', models.DateField()),
                ('cvc_code', models.CharField(max_length=3)),
                ('card_number', models.CharField(max_length=18)),
            ],
            options={
                'db_table': 'provider_card_detail',
            },
        ),
        migrations.CreateModel(
            name='SendFax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField(default=0, max_length=2)),
                ('weekno', models.IntegerField(default=0)),
                ('pre_ciq', models.BooleanField(default=False)),
                ('post_ciq', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'fax_send',
            },
        ),
        migrations.CreateModel(
            name='VideoSessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url', models.TextField()),
                ('content', models.TextField()),
                ('review_content', models.TextField()),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'video_sessions',
            },
        ),
        migrations.CreateModel(
            name='VideoSessionsCompleted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('completed', models.BooleanField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'video_session_patients',
            },
        ),
        migrations.CreateModel(
            name='VideoViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('view_video', models.IntegerField()),
            ],
            options={
                'db_table': 'patient_video_view',
            },
        ),
        migrations.CreateModel(
            name='VideoQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('main_question', models.TextField()),
                ('correct_ans', models.TextField()),
                ('options', models.TextField()),
                ('status', models.IntegerField()),
                ('type', models.IntegerField(default=1)),
                ('video_sessions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.videosessions')),
            ],
            options={
                'db_table': 'video_questions',
            },
        ),
        migrations.CreateModel(
            name='VideoAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video_questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.videoquestions')),
            ],
            options={
                'db_table': 'video_answers',
            },
        ),
        migrations.CreateModel(
            name='SleepDiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(max_length=10, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time_went_to_bed', models.CharField(max_length=10, null=True)),
                ('lights_out', models.CharField(max_length=10, null=True)),
                ('minutes_fall_asleep', models.IntegerField(null=True)),
                ('out_of_bed', models.CharField(max_length=10, null=True)),
                ('time_fell_asleep', models.CharField(max_length=10, null=True)),
                ('time_got_up', models.CharField(max_length=10, null=True)),
                ('minutes_fellback_sleep', models.IntegerField(null=True)),
                ('desire_wakeup_time', models.CharField(max_length=10, null=True)),
                ('no_of_times_awakend', models.IntegerField(null=True)),
                ('total_time_awakened', models.IntegerField(null=True)),
                ('number_of_naps', models.IntegerField(null=True)),
                ('totlatime_napping_minutes', models.IntegerField(null=True)),
                ('day_avg', models.CharField(max_length=10, null=True)),
                ('is_updated', models.BooleanField(default=True)),
                ('time_in_bed', models.CharField(max_length=8, null=True)),
                ('total_sleep_time', models.CharField(max_length=8, null=True)),
                ('sleep_efficiency', models.CharField(max_length=8, null=True)),
                ('problem_falling_asleep', models.CharField(blank=True, max_length=8)),
                ('overslept', models.CharField(blank=True, max_length=10)),
                ('awake_during_night', models.CharField(blank=True, max_length=8)),
                ('awake_too_early', models.CharField(blank=True, max_length=8)),
                ('delayed_getting_up', models.CharField(blank=True, max_length=8)),
                ('total_gotup_time', models.CharField(max_length=10, null=True)),
                ('comment', models.TextField(max_length=2000, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Providerhandbooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_remark', models.CharField(max_length=2000)),
                ('provider_remark', models.CharField(max_length=2000)),
                ('week_number', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'provider_handbooks',
            },
        ),
    ]
