# Generated by Django 3.2.9 on 2024-02-19 16:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('passwordstr', models.CharField(default='', max_length=100)),
                ('first_login', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('active_patient', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('role_id', models.IntegerField(default=False)),
                ('isprovider', models.BooleanField(default=False)),
                ('isverified', models.BooleanField(default=False)),
                ('package', models.IntegerField(default=False)),
                ('verifiedcode', models.CharField(default='', max_length=30)),
                ('user_agent', models.CharField(default='', max_length=50)),
                ('admin', models.BooleanField(default=False)),
                ('document_id', models.CharField(default='', max_length=250)),
                ('signing_link_1', models.URLField(blank=True, null=True)),
                ('signing_link_2', models.URLField(blank=True, null=True)),
                ('invite_id', models.CharField(default='', max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Add_provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(max_length=10)),
                ('pid', models.CharField(max_length=10)),
                ('date', models.DateField(blank=True, default=datetime.date.today)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ma_record',
            },
        ),
        migrations.CreateModel(
            name='Provider_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'provider_type',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('contact_no', models.CharField(max_length=20)),
                ('driving_license_front_img', models.ImageField(default='/media/default.png', upload_to='user_pics')),
                ('driving_license_back_img', models.ImageField(default='/media/default.png', upload_to='user_pics')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('package_no', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'patients',
            },
        ),
        migrations.CreateModel(
            name='RefPatient',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
                ('provider_id', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('contact_no', models.CharField(max_length=20)),
                ('driving_license_front_img', models.ImageField(default='/media/default.png', upload_to='user_pics')),
                ('driving_license_back_img', models.ImageField(default='/media/default.png', upload_to='user_pics')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('package_no', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ref_patients',
            },
        ),
        migrations.CreateModel(
            name='Provider_Verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_position', models.IntegerField(max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'provider_verification',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=20)),
                ('license_state', models.CharField(max_length=20)),
                ('type_of_practice', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('practice_name', models.CharField(max_length=50)),
                ('practice_phone_number', models.CharField(max_length=20)),
                ('practice_address', models.CharField(max_length=200)),
                ('driving_license_front_img', models.ImageField(default='/media/default.png', upload_to='user_pics')),
                ('driving_license_back_img', models.ImageField(default='/media/default.png', upload_to='user_pics')),
                ('provider_image', models.ImageField(default='/media/patient.png', upload_to='user_pics')),
                ('medical_license_image', models.ImageField(default='/media/default.png', upload_to='user_pics')),
                ('fax_no', models.CharField(max_length=20)),
                ('primary_care_office_name', models.CharField(max_length=100)),
                ('primary_care_doctor_name', models.CharField(max_length=100)),
                ('primary_care_doctor_id', models.CharField(max_length=50, null=True)),
                ('provider_ref', models.CharField(max_length=50)),
                ('total_patients', models.IntegerField(default=0)),
                ('subscription_status', models.CharField(max_length=100, null=True)),
                ('provider_type', models.CharField(max_length=100)),
                ('package_type', models.CharField(max_length=250)),
                ('flag', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'providers',
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('contact_no', models.CharField(max_length=20)),
                ('license_state', models.CharField(max_length=20)),
                ('type_of_practice', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('practice_name', models.CharField(max_length=50)),
                ('practice_phone_number', models.CharField(max_length=20)),
                ('practice_address', models.CharField(max_length=200)),
                ('driving_license_front_img', models.ImageField(default='/media/default.png', upload_to='user_pics')),
                ('driving_license_back_img', models.ImageField(default='/media/default.png', upload_to='user_pics')),
                ('provider_image', models.ImageField(default='/media/default.png', upload_to='user_pics')),
                ('fax_no', models.CharField(max_length=20)),
                ('primary_care_office_name', models.CharField(max_length=100)),
                ('primary_care_doctor_name', models.CharField(max_length=100)),
                ('doctor_ref_number', models.CharField(max_length=100)),
                ('patient_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientPaymentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('card_no', models.CharField(max_length=30)),
                ('card_expiry', models.CharField(max_length=30)),
                ('card_cvv', models.CharField(max_length=5)),
                ('card_address', models.CharField(max_length=200)),
                ('card_city', models.CharField(max_length=20)),
                ('card_state', models.CharField(max_length=20)),
                ('card_zip_code', models.CharField(max_length=20)),
                ('patient_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_to', models.EmailField(max_length=60)),
                ('invited_type', models.CharField(choices=[('provider', 'Provider'), ('MA', 'MA')], max_length=10)),
                ('date', models.DateField(blank=True, default=datetime.date.today)),
                ('invitation_accept', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invitation',
            },
        ),
    ]
