# Generated by Django 3.2.9 on 2024-03-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='subscription_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
