# Generated by Django 3.2.9 on 2024-03-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_provider_subscription_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='subscription_type',
            field=models.CharField(default='package', max_length=100),
        ),
    ]
