# Generated by Django 3.2.9 on 2024-03-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_provider_subscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='coupon_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
