# Generated by Django 3.2.9 on 2024-09-16 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Permissions', '0001_initial'),
        ('accounts', '0007_auto_20240819_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Permissions.userrole'),
        ),
    ]
