"""
Django settings for cognisleep project.

Generated by 'django-admin startproject' using Django 2.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from django.contrib.messages import constants as messages

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'cb*%&sggtobq@l(z4!_h=c4c5+$b=z)&_xam6d1b3)v@bmesd+'
# SECRET_KEY = '(7=&+=v@y)29!t$$)c!471j_ox4-o39mzbz0dyd5z0r=7r_4d)'
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
# ALLOWED_HOSTS = env('DJANGO_ALLOWED_HOSTS').split(',')
# heroku config:set 'DJANGO_ALLOWED_HOSTS' = 'cognisleep.com,www.cognisleep.com,3.17.173.5'
# ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'rest_framework',
    'knox',
    'crispy_forms',
    'crispy_bootstrap4',
    'taketester.apps.TaketesterConfig',
    'accounts.apps.AccountsConfig',
    'backend',
    'dashboard',
    # 'payments',
    'Permissions',
    'payments.apps.PaymentsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_user_agents',
    'dashboard.templatetags',
    'corsheaders',
    'rest_framework.authtoken',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'cogni.middleware.LoginGuestRequiredMiddleware',
    'django_user_agents.middleware.UserAgentMiddleware',

]

CORS_ORIGIN_ALLOW_ALL = True

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8001",
    "http://localhost:8000",
    "http://127.0.0.1:8001",
    "http://127.0.0.1:8000",
]
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]
ROOT_URLCONF = 'cogni.urls'
# STATICFILES_DIRS = [
#   os.path.join(BASE_DIR, "static"),
#   'static/',
# ]

MESSAGE_TAGS = {
    messages.ERROR: 'danger'
}

BASE_URL = "http://127.0.0.1:8000/"

# BASE_URL = "https://cognisleep.com/"  # "http://10.138.2.58/"
VIDEO_URL = "https://cognisleep.desenador.com/"
BASE_TITLE = 'CogniSleep'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.media',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cogni.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES':
        ('knox.auth.TokenAuthentication',
         'rest_framework.authentication.TokenAuthentication',
         ),
    'DEFAULT_PERMISSION_CLASSES': (
            'rest_framework.permissions.IsAuthenticated',
        ),

}

from datetime import timedelta

REST_KNOX = {
    'USER_SERIALIZER': 'accounts.serializer.UserSerializer',
    'TOKEN_TTL': timedelta(hours=24 * 7),
}

#
# ps:  +6f{6q^b!3S,


DATABASES = {

    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    # }

    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'cogni1',
        'USER': 'root',
        'PASSWORD': 'my-password',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
        }
    }

    # 'default': {
    #    'ENGINE': 'django.db.backends.mysql',
    #    'NAME': 'cognisleep',
    #    'USER': 'root',
    #    'PASSWORD': 'asd123',
    #    'HOST': '127.0.0.1',
    #    'PORT': '8889',
    #    'OPTIONS': {
    #        'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
    #    }
    # }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
# STATIC_ROOT = '/home/ubuntu/django/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# MEDIA_URL = '/home/ubuntu/django/media/'
# Increase the maximum upload size allowed for files (in bytes)
DATA_UPLOAD_MAX_MEMORY_SIZE = 1024 * 1024 * 20  # 20 MB, adjust as needed

# Increase the maximum size allowed for files uploaded via a multipart/form-data POST
FILE_UPLOAD_MAX_MEMORY_SIZE = 1024 * 1024 * 20  # 20 MB, adjust as needed

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap4"

CRISPY_TEMPLATE_PACK = "bootstrap4"

LOGIN_REDIRECT_URL = '/dashboard'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = '/accounts/login'
STRIPE_PUBLISHABLE_KEY = 'pk_test_51LBfcLKxLHATWwe7cusrpfripSNOxKgdyh2UyjcwyHcY7xtrvZXiIy2zFPbodDcswI2SryjHjYHp01JSztR3Cwa000s6AoRU7M'
STRIPE_SECRET_KEY = 'sk_test_51LBfcLKxLHATWwe7yJr8k5XYrxGAlb8LdEhmnWaRm2Q8Z2wzKKT2MYf9sjZDzHnfZzpdVtPXw53CUzys8hwtpXbd00QssamM1K'

ADMIN_SITE_HEADER = "Cognisleep Administration"
AUTH_USER_MODEL = 'accounts.User'
LOGIN_GUEST_URL = '/login'



LOGIN_NOT_REQUIRED_URLS = [
    r'^accounts/logout/$',
    r'^guesloginsession/$'
]
# SECURE_SSL_REDIRECT = True

# os.environ['HTTPS'] = "on"
# os.environ['wsgi.url_scheme'] = 'https'
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# EMAIL_HOST = 'mocha3021.mochahost.com'
# EMAIL_PORT = 465
# EMAIL_HOST_USER = 'iehsan77@techiedev.com'
# EMAIL_HOST_PASSWORD = 'XtSx%W/^JoL//4C)@n'
# EMAIL_USE_SSL = True
# EMAIL_USE_TLS = False
# EMAIL_FROM = 'iehsan77@techiedev.com'


# EMAIL_HOST = 'email-smtp.us-east-2.amazonaws.com'
# EMAIL_PORT = 465
# EMAIL_HOST_USER = 'AKIA4MJNMUFEQWGU74JX'
# EMAIL_HOST_PASSWORD = 'BE80EJiCFgwscWhUcosoJg3x2jcTNIhBC+vhetWsd3mW'
# EMAIL_USE_SSL = True
# EMAIL_USE_TLS = False
# EMAIL_FROM = 'info@cognisleep.com'

EMAIL_HOST = 'mail.cognisleep.com'
EMAIL_PORT = 465
EMAIL_HOST_USER = 'info@cognisleep.com'
EMAIL_HOST_PASSWORD = 'GoDrGetThemToSleep1990'  # 'Getintosee1990!'
EMAIL_USE_SSL = True
EMAIL_USE_TLS = False
EMAIL_FROM = 'info@cognisleep.com'

SESSION_EXPIRE_AT_BROWSER_CLOSE = True

RECAPTCHA_PUBLIC_KEY = '6Lf37LQUAAAAAIHIJDdoPYLF0pLXZ_zFwqbV2AAn'
RECAPTCHA_PRIVATE_KEY = '6Lf37LQUAAAAAGVAcRNbahrf-xY8U8BIlxopRWZd'