# Generated by Django 3.2.9 on 2024-02-19 16:45

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealBreakerQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('deal_breaker_id', models.IntegerField(default=0)),
                ('type', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Guest_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('[a-zA-Z][a-zA-Z ]+', 'Only alpha characters are allowed.')])),
                ('last_name', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('[a-zA-Z][a-zA-Z ]+', 'Only alpha characters are allowed.')])),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('txt_insomnia_points', models.CharField(max_length=200)),
                ('txt_insomnia_msg', models.CharField(max_length=500)),
                ('result_value', models.IntegerField(null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Options_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qid', models.CharField(editable=False, max_length=4, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('option1', models.TextField()),
                ('option2', models.TextField()),
                ('option3', models.TextField()),
                ('option4', models.TextField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('is_pre', models.BooleanField(default=False)),
                ('is_post', models.BooleanField(default=False)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TakeTester_questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('question_slug', models.TextField(default='')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=datetime.date.today)),
                ('option_selected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taketester.options_new')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taketester.question_new')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TakeTester_answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taketester.taketester_questions')),
            ],
        ),
        migrations.CreateModel(
            name='PatientAnswer',
            fields=[
                ('qid', models.CharField(editable=False, max_length=4, primary_key=True, serialize=False)),
                ('pre_answer', models.TextField()),
                ('post_answer', models.TextField()),
                ('result', models.TextField()),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='options_new',
            name='question_new',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taketester.question_new'),
        ),
        migrations.CreateModel(
            name='DealBreakerNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taketester.dealbreakerquestions')),
            ],
        ),
    ]
